import base64
import fnmatch
import io
import json
import tarfile
from dataclasses import dataclass
from pathlib import Path

from krun.errors import KrunError
from krun.project import Project

DEFAULT_IGNORES = (
    ".git",
    ".git-data",
    ".krun",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".env*",
    "kaggle.json",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
    "id_rsa",
    "id_ed25519",
    "*.pyc",
)
MAX_PACKAGE_BYTES = 20 * 1024 * 1024


@dataclass(frozen=True)
class PackageResult:
    runner: Path
    file_count: int
    source_bytes: int


def prepare_workspace(
    project: Project,
    workspace: Path,
    arguments: list[str],
    input_paths: list[Path] | None = None,
) -> PackageResult:
    workspace.mkdir(parents=True, exist_ok=True)
    files = collect_project_files(project.root)
    for input_path in input_paths or []:
        candidates = input_path.rglob("*") if input_path.is_dir() else (input_path,)
        files.extend(path for path in candidates if path.is_file() and not path.is_symlink())
    files = sorted(set(files))
    source_bytes = sum(path.stat().st_size for path in files)
    if source_bytes > MAX_PACKAGE_BYTES:
        size_mb = source_bytes / (1024 * 1024)
        raise KrunError(
            f"Project package is {size_mb:.1f} MB; the MVP limit is "
            f"{MAX_PACKAGE_BYTES // (1024 * 1024)} MB. Use a Kaggle Dataset for large inputs."
        )

    payload = _archive(project.root, files)
    entrypoint = project.entrypoint.relative_to(project.root).as_posix()
    requirements = (
        project.requirements.relative_to(project.root).as_posix()
        if project.requirements
        else None
    )
    runner_path = workspace / "runner.py"
    runner_path.write_text(
        _render_runner(
            payload=payload,
            entrypoint=entrypoint,
            arguments=arguments,
            requirements=requirements,
            install_project=project.requirements is None and project.pyproject is not None,
            outputs=project.config.outputs,
        ),
        encoding="utf-8",
    )
    return PackageResult(runner=runner_path, file_count=len(files), source_bytes=source_bytes)


def collect_project_files(root: Path) -> list[Path]:
    patterns = list(DEFAULT_IGNORES)
    ignore_file = root / ".krunignore"
    if ignore_file.is_file():
        patterns.extend(
            line.strip()
            for line in ignore_file.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        )

    files: list[Path] = []
    for path in sorted(root.rglob("*")):
        if path.is_symlink() or not path.is_file():
            continue
        relative = path.relative_to(root)
        if not _is_ignored(relative, patterns):
            files.append(path)
    return files


def _is_ignored(path: Path, patterns: list[str]) -> bool:
    value = path.as_posix()
    parts = path.parts
    for raw_pattern in patterns:
        pattern = raw_pattern.strip().lstrip("/").rstrip("/")
        if not pattern:
            continue
        if "/" not in pattern and any(fnmatch.fnmatch(part, pattern) for part in parts):
            return True
        if fnmatch.fnmatch(value, pattern) or fnmatch.fnmatch(value, f"{pattern}/**"):
            return True
    return False


def _archive(root: Path, files: list[Path]) -> str:
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as archive:
        for path in files:
            archive.add(path, arcname=path.relative_to(root).as_posix(), recursive=False)
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def _render_runner(
    payload: str,
    entrypoint: str,
    arguments: list[str],
    requirements: str | None,
    install_project: bool,
    outputs: list[str],
) -> str:
    return f'''# Generated by krun. Do not edit.
import base64
import io
import json
import os
from pathlib import Path
import runpy
import shutil
import subprocess
import sys
import tarfile

PAYLOAD = {payload!r}
ENTRYPOINT = {entrypoint!r}
ARGUMENTS = {json.dumps(arguments)!r}
REQUIREMENTS = {requirements!r}
INSTALL_PROJECT = {install_project!r}
OUTPUTS = {json.dumps(outputs)!r}

working = Path(os.environ.get("KRUN_WORKING_DIR", "/kaggle/working"))
project = working / "krun_project"
artifacts = working / "krun_outputs"
project.mkdir(parents=True, exist_ok=True)
with tarfile.open(fileobj=io.BytesIO(base64.b64decode(PAYLOAD)), mode="r:gz") as archive:
    try:
        archive.extractall(project, filter="data")
    except TypeError:
        # Python 3.10 lacks extraction filters. The archive is generated by
        # krun from regular files with project-relative names only.
        archive.extractall(project)

if REQUIREMENTS:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", str(project / REQUIREMENTS)])
elif INSTALL_PROJECT:
    subprocess.check_call([sys.executable, "-m", "pip", "install", str(project)])

os.chdir(project)
sys.path.insert(0, str(project))
sys.argv = [ENTRYPOINT, *json.loads(ARGUMENTS)]
try:
    runpy.run_path(str(project / ENTRYPOINT), run_name="__main__")
finally:
    artifacts.mkdir(parents=True, exist_ok=True)
    for configured in json.loads(OUTPUTS):
        source = project / configured
        if not source.exists():
            continue
        destination = artifacts / configured.rstrip("/")
        destination.parent.mkdir(parents=True, exist_ok=True)
        if source.is_dir():
            shutil.copytree(source, destination, dirs_exist_ok=True)
        else:
            shutil.copy2(source, destination)
'''
